### ISSUE TITLE
Pages for threading macros cannot be found

### ISSUE THREAD

**Issue by iku000888** [zk/clojuredocs#149] opened 2016-12-15 03:52 UTC
It used to show just fine, but now the site returns a 404.
https://clojuredocs.org/clojure.core/%3C=

They still do show up in the search result, but clicking the link returns the same result.
https://clojuredocs.org/search?q=%3E

Looks like any URL string containing a ">" are having problems.

**Comment by ChristopherL-STCU** [comment] 2016-12-15 23:14
Any with a greater than ***or*** less than

**Comment by zk** [comment] 2016-12-21 20:53
I recently made some big changes (e.g. less to garden conversion), must have broken this. I'll take a look later today. https://github.com/zk/clojuredocs/blob/35581683bd2357c82dadfa0fb9f8486ad0d67dc4/src/clj/clojuredocs/pages.clj#L358

**Comment by zk** [comment] 2016-12-22 01:33
Fixed by f73dfe4a8822d52cd0fa7d45bb327a4b8d98e07f

**Closed by zk** 2016-12-22 01:33 UTC

**Comment by zk** [comment] 2016-12-22 01:36
I wasn't able to track down the root cause of this regression (although admittedly I didn't look very hard). AFAICT decoding of the URL encoded var name was done automatically somewhere in the ring stack, and that behavior may have changed with I bumped one of the dependencies recently.

**Comment by iku000888** [comment] 2016-12-22 02:15
@zk Thanks for the quick response!

**Comment by zk** [comment] 2016-12-22 02:18
@iku000888 Thanks for taking the time to report it 🙏
