### ISSUE TITLE
Search field goes into infinite loop in Chrome

### ISSUE THREAD

**Issue by hipitihop** [zk/clojuredocs#183] opened 2018-01-19 00:46 UTC
When I type anything into the search field in Chrome on the home page or while on another doc page, devtools shows large number of errors `Couldn't render ac entry:`
Chrome Version 63.0.3239.132 (Official Build) (64-bit) However works on Firefox 57.0.4 (64-bit)

This may or may not be related to issue #182

![image](https://user-images.githubusercontent.com/4626024/35128977-0000df16-fd05-11e7-9809-d7d4d09442f2.png)

**Comment by drobban** [comment] 2018-01-19 09:09
Same for Chrome Version 62.0.3202.62 (Official Build) (64-bit)

**Comment by jlesquembre** [comment] 2018-01-19 12:39
I'm also having the issue, seems to happen only if you are not logged in.

**Comment by zk** [comment] 2018-01-20 06:38
Hey guys, thanks for reporting. I'm having trouble reproducing this on 63.0.3239.132 (Official Build) (64-bit), any more info on steps you took to get to this state?

**Comment by zk** [comment] 2018-01-20 07:22
Nevermind, was able to repro. It's https:// specific, I was using http://

**Comment by drobban** [comment] 2018-01-22 08:50
can confirm. That the http:// page content doesn't reproduce the same problem for Chrome Version 62.0.3202.62 (Official Build) (64-bit)

**Comment by zk** [comment] 2018-02-01 19:51
Yeah still failing to repro. Running SSL locally via ngrok didn't work, trying other options.

**Comment by zk** [comment] 2018-02-01 21:10
Fixed by 5fca13c67894a974eec01608a78c3cad41c55072.

Turns out parsing headers was broken, which was causing the client to miss the edn content-type header and subsequently not convert the body from a string to edn. Headers in the response were slightly different over http vs https.

The rendering loop was iterating over the response body string, instead of the seq of autocomplete results, making it look like an infinite-loop type bug, but in actuality the error message at the console was printed for each character in the string, often ~1k characters.

**Closed by zk** 2018-02-01 21:10 UTC
