### ISSUE TITLE
Some symbolic names in the search results lead to 404 error page.

### ISSUE THREAD

**Issue by mingp** [zk/clojuredocs#152] opened 2016-12-19 04:12 UTC
When searching for some symbolic names (example: `->`), the autocomplete shows a result with a link (example: http://clojuredocs.org/clojure.core/->), but then then clicking that link and visiting that URL returns a 404 error page. Is there perhaps some issue with special character escaping going on?

**Comment by ramimoshe** [comment] 2016-12-21 10:16
how can we get this docs until the fix? (workaround?)

**Comment by dhineshns** [comment] 2016-12-21 15:06
you can refer this meanwhile. https://www.conj.io/store/v1/org.clojure/clojure/1.8.0/clj/clojure.core/cond-%3E

**Comment by rebcabin** [comment] 2016-12-21 20:09
ditto for `cond->` and `cond->>`

**Comment by zk** [comment] 2016-12-21 20:47
Dupe of #149

**Closed by zk** 2016-12-21 20:47 UTC
